name: PR CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: npm install
        run: npm install
      - name: test
        run: npm run test
  release:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: npm ci
        run: npm ci
      - name: build
        run: npm run build
      - name: release
        run: npm run semantic-release
